// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uclgrfiwnaqfwmyqrvma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbGdyZml3bmFxZndteXFydm1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjcyMTksImV4cCI6MjA2NTE0MzIxOX0.qk-uCtz5SFr8CKRfdxRif3gtoK36ds1z06E5MbnT0nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);